CREATE TABLE receipt(
	id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    send_company_name varchar(255) NOT NULL,
    sender_company_address varchar(255) NOT NULL,
    sender_company_email varchar(255) NOT NULL,
    sender_company_website varchar(255) NOT NULL,
    sender_fname varchar(255) NOT NULL,
    sender_lname varchar(255) NOT NULL,
   	origin_office varchar(255) NOT NULL,
    product_name varchar(255) NOT NULL,
    quantity int(11) NOT NULL,
    shipping_cost int(11) NOT NULL,
    clearance_cost int(11) NOT NULL,
    description varchar(1000) NOT NULL,
    logo varchar(1000) NOT NULL,
    receiver_fname varchar(255) NOT NULL,
    receiver_lname varchar(255) NOT NULL,
    receiver_address varchar(255) NOT NULL,
    receiver_phone int(11) NOT NULL,
    destination_office varchar(255) NOT NULL,
    order_id int(11) NOT NULL,
    tracking_no int(11) NOT NULL,
    del_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);